import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[shell]
program = "/bin/zsh"
args = ["--login"]

[env]
TERM = "xterm-256color"
STARSHIP_CONFIG = "/Users/yourusername/.config/starship.toml"

[window]
padding.x = 10
padding.y = 9

decorations = "Buttonless"

dimensions.columns = 230
dimensions.lines = 65

position.x = 200
position.y = 100

startup_mode = "Windowed"

opacity = 0.7
# blur = true

option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font Mono"

size = 9.5

